### ISSUE TITLE
Design: new components required

### ISSUE THREAD

**Issue by Juliana-t** [catalpainternational/canoe#291]
## Overview
For the offline distribution of contents, a number of visual components are required.
Canoe will be converted into an [Android app](https://github.com/catalpainternational/canoe-backend/issues/80), an app icon is being developed by Daniel under the Brand Identity work.

## Conditions of satisfaction
- [ ] There is 'offline' label that is displayed when the content (lesson/course) was downloaded to the user device and is available to be accessed offline. [View User Story #83](https://github.com/catalpainternational/canoe-backend/issues/83), [View User Story #82](https://github.com/catalpainternational/canoe-backend/issues/82) and [User story #81](https://github.com/catalpainternational/canoe-backend/issues/81)
- [ ] When the download of a course/lesson fails, there is an alert message. [View User Story 83](https://github.com/catalpainternational/canoe-backend/issues/83), [View User Story #82](https://github.com/catalpainternational/canoe-backend/issues/82) and [User story #81](https://github.com/catalpainternational/canoe-backend/issues/81)
  - [ ] "There was a problem while downloading the content. Please close the app and open it again"
- [ ] When there isn't enough storage space on the device to store the content. [View User Story 83], [View User Story #82](https://github.com/catalpainternational/canoe-backend/issues/82) and [User story #81](https://github.com/catalpainternational/canoe-backend/issues/81)(https://github.com/catalpainternational/canoe-backend/issues/83)
  - [ ] “There isn’t enough storage space on your device. Please remove contents from your device and try again”

## Screens designed under the new DS - please review and confirm
- [ ] When a content isn't available offline, there is a button to download it. [View User Story #82](https://github.com/catalpainternational/canoe-backend/issues/82)
  - [ ] Design to conform if this is the [correct mockup](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/433355448/comments?scrollOffset=4736#project_console)
- [ ] When there are downloads in progress, there is an alert message
  - [ ] Design to confirm if this is the [correct mockup](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/433355448/comments?scrollOffset=4736#project_console)
- [ ] When downloads are completed, there is an alert message
  - [ ] Design to confirm if this is the [correct mockup](https://projects.invisionapp.com/d/main?origin=v7#/console/20251865/433355449/comments?scrollOffset=4736#project_console)

**Comment by andrewwapling** [comment]
Hi @Juliana-t , Thanks for getting this through to me. Just confirming that this task is currently underway and I'll comment back against each user story issue with details and design solutions with prototype links for review.

Thanks again, Andy

**Comment by Juliana-t** [comment]
Thanks Andy, when you have something for review, please tag me on Slack or
GH so I can have a look and give you feedback asap

**Comment by andrewwapling** [comment]
Hi @Juliana-t , A pleasure, will do. I'll tag you in any GH updates so that you get an alert and also follow up on Slack. Thanks again, Andy

**Comment by andrewwapling** [comment]
Hi @Juliana-t & @PeteCoward ,

Just adding to this to confirm correct designs in response to 'Screens designed under the new DS - please review and confirm' banner listed in the original issue above.

• When a content isn't available offline, there is a button to download it
Please see below direct link to screen design within prototype to a course detail screen that contains the Download to offline function: https://invis.io/52Y02L9YTRF#/433355445_5A-_Course_Detail_-_Clean

• When there are downloads in progress, there is an alert message
Please see below direct link to screen design within prototype showing a toast notification of a download in progress: https://invis.io/52Y02L9YTRF#/439933751_5D-_Course_Detail_-_Download_In_Progress 

• When downloads are completed, there is an alert message
Please see below direct link to screen design within prototype that displays the download complete toast notification: https://invis.io/52Y02L9YTRF#/439933752_5D-_Course_Detail_-_Download_Success

Let me know if you're happy with the above solutions or have any queries at all.

Thanks again, Andy

**Comment by andrewwapling** [comment]
Hi @Juliana-t @PeteCoward @davidcatalpa , 

Just a recap on the download label integration. Please see link below to the range of design solutions for consideration that have been created to date.

1. Clean Course Listing (i.e. original design sans download label): https://invis.io/52Y02L9YTRF#/440455736_2B-_Course_Listing_-_Category_-_Alt
2. Course Listing Flag: https://invis.io/52Y02L9YTRF#/441043807_2B-_Course_Listing_-_Category_-_Alt_1
3. Course Listing Lozenge: https://invis.io/52Y02L9YTRF#/441043808_2B-_Course_Listing_-_Category_-_Alt_2
4. Course Listing Text Flag: https://invis.io/52Y02L9YTRF#/441043809_2B-_Course_Listing_-_Category_-_Alt_3
5. Course Listing Opaque Lozenge: https://invis.io/52Y02L9YTRF#/441043810_2B-_Course_Listing_-_Category_-_Alt_4

My strong recommendation would be the clean and simple Text Flag approach #4. The other options are quite bold and compete with more important elements within the course and lesson cards. I feel the cleanliness and simplicity of the text flag approach is the most integrated solution.

Look forward to hearing your thoughts.

Thanks again, Andy
